apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: excel-postgres
  name: excel-postgres
spec:
  containers:
  - env:
    - name: POSTGRES_DB
      value: excel_db
    - name: POSTGRES_PASSWORD
      value: password
    - name: POSTGRES_USER
      value: excel_root
    image: excel-postgres
    name: excel-postgres
    ports:
    - containerPort: 5432
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/postgresql/data/
      name: excel-postgres-claim0
  hostname: excel_postgres
  restartPolicy: Never
  volumes:
  - name: excel-postgres-claim0
    persistentVolumeClaim:
      claimName: excel-postgres-claim0
status: {}
