apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: excel-redis
  name: excel-redis
spec:
  containers:
  - image: excel-redis
    name: excel-redis
    ports:
    - containerPort: 6379
    resources: {}
    volumeMounts:
    - mountPath: /data
      name: excel-redis-claim0
  hostname: excel_redis
  restartPolicy: Never
  volumes:
  - name: excel-redis-claim0
    persistentVolumeClaim:
      claimName: excel-redis-claim0
status: {}
