apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: excel-nginx
  name: excel-nginx
spec:
  containers:
  - image: nginx:mainline
    name: excel-nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: /code
      name: excel-nginx-claim0
    - mountPath: /etc/nginx/conf.d/default.conf
      name: excel-nginx-claim1
    - mountPath: /var/log/nginx
      name: excel-nginx-claim2
  hostname: excel_nginx
  restartPolicy: Never
  volumes:
  - name: excel-nginx-claim0
    persistentVolumeClaim:
      claimName: excel-nginx-claim0
  - name: excel-nginx-claim1
    persistentVolumeClaim:
      claimName: excel-nginx-claim1
  - name: excel-nginx-claim2
    persistentVolumeClaim:
      claimName: excel-nginx-claim2
status: {}
