version: '3.7'

services:
  excel_postgres:
    container_name: "excel_postgres"
    build: ./conf/postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=excel_root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=excel_db
    hostname: "excel_postgres"
    ports:
      - "5432:5432"
    networks:
      excel_net:
        aliases:
          - excel_postgres
  excel_phpfpm:
    container_name: "excel_phpfpm"
    build: ./conf/php
    restart: always
    depends_on:
      - excel_postgres
      - excel_redis
    volumes:
      - ./../:/code
      - ./conf/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "9000:9000"
    hostname: "excel_phpfpm"
    networks:
      excel_net:
        aliases:
          - excel_phpfpm
  excel_nginx:
    container_name: "excel_nginx"
    image: nginx:mainline
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - excel_phpfpm
    volumes:
      - ./../:/code
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/log:/var/log/nginx
    hostname: "excel_nginx"
    networks:
      excel_net:
        aliases:
          - excel_nginx
  excel_redis:
    container_name: "excel_redis"
    build: ./conf/redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    hostname: "excel_redis"
    networks:
      excel_net:
        aliases:
          - excel_redis
networks:
  excel_net:
    external: false
